In [45]:
import numpy as np
import pandas as pd
import pulp as plp #biblioteca de programacao linear
import matplotlib.pyplot as plt

In [46]:
#lendo a base de dados que montamos do nan
df_nan = pd.read_excel("df_nan.xlsx")
display(df_nan)

    Rótulo Hora Início  Hora Fim  Número Médio Ligantes  nan
0        1    00:00:00  00:15:00                    601   14
1        2    00:15:00  00:30:00                    190    7
2        3    00:30:00  00:45:00                    180    8
3        4    00:45:00  01:00:00                    177    7
4        5    01:00:00  01:15:00                    162    6
..     ...         ...       ...                    ...  ...
91      92    22:45:00  23:00:00                    920   23
92      93    23:00:00  23:15:00                    897   21
93      94    23:15:00  23:30:00                    571   15
94      95    23:30:00  23:45:00                    560   14
95      96    23:45:00  00:00:00                    590   18

[96 rows x 5 columns]

In [47]:
#garantindo que a coluna de horarios ta no formato de hora 
display(pd.to_datetime(df_nan["Hora Início"]))

/var/folders/rx/xxpdxt0n29sdd2llt41cgjvm0000gn/T/ipykernel_51993/2175329874.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  display(pd.to_datetime(df_nan["Hora Início"]))

0    2026-06-28 00:00:00
1    2026-06-28 00:15:00
2    2026-06-28 00:30:00
3    2026-06-28 00:45:00
4    2026-06-28 01:00:00
             ...
91   2026-06-28 22:45:00
92   2026-06-28 23:00:00
93   2026-06-28 23:15:00
94   2026-06-28 23:30:00
95   2026-06-28 23:45:00
Name: Hora Início, Length: 96, dtype: datetime64[us]

In [48]:
#Trocando as colunas de horas pro horario correto

df_nan["Hora Início"] = pd.to_datetime(df_nan["Hora Início"])

df_nan["Hora Fim"] = pd.to_datetime(df_nan["Hora Fim"])

display(df_nan)

/var/folders/rx/xxpdxt0n29sdd2llt41cgjvm0000gn/T/ipykernel_51993/2098643794.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_nan["Hora Início"] = pd.to_datetime(df_nan["Hora Início"])
/var/folders/rx/xxpdxt0n29sdd2llt41cgjvm0000gn/T/ipykernel_51993/2098643794.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_nan["Hora Fim"] = pd.to_datetime(df_nan["Hora Fim"])

    Rótulo         Hora Início            Hora Fim  Número Médio Ligantes  nan
0        1 2026-06-28 00:00:00 2026-06-28 00:15:00                    601   14
1        2 2026-06-28 00:15:00 2026-06-28 00:30:00                    190    7
2        3 2026-06-28 00:30:00 2026-06-28 00:45:00                    180    8
3        4 2026-06-28 00:45:00 2026-06-28 01:00:00                    177    7
4        5 2026-06-28 01:00:00 2026-06-28 01:15:00                    162    6
..     ...                 ...                 ...                    ...  ...
91      92 2026-06-28 22:45:00 2026-06-28 23:00:00                    920   23
92      93 2026-06-28 23:00:00 2026-06-28 23:15:00                    897   21
93      94 2026-06-28 23:15:00 2026-06-28 23:30:00                    571   15
94      95 2026-06-28 23:30:00 2026-06-28 23:45:00                    560   14
95      96 2026-06-28 23:45:00 2026-06-28 00:00:00                    590   18

[96 rows x 5 columns]

In [49]:
df_nan["Hora Início"] = \
    df_nan["Hora Início"].dt.strftime("%H:%M")

df_nan["Hora Fim"] = \
    df_nan["Hora Fim"].dt.strftime("%H:%M")

display(df_nan)

    Rótulo Hora Início Hora Fim  Número Médio Ligantes  nan
0        1       00:00    00:15                    601   14
1        2       00:15    00:30                    190    7
2        3       00:30    00:45                    180    8
3        4       00:45    01:00                    177    7
4        5       01:00    01:15                    162    6
..     ...         ...      ...                    ...  ...
91      92       22:45    23:00                    920   23
92      93       23:00    23:15                    897   21
93      94       23:15    23:30                    571   15
94      95       23:30    23:45                    560   14
95      96       23:45    00:00                    590   18

[96 rows x 5 columns]

In [50]:
df_nad = pd.read_excel("df_nad.xlsx")
display(df_nad)

   regime  enc  nad
0       3  540  200
1       4  680  200
2       6  960  200

In [51]:
from itertools import product

In [52]:
regimes = df_nad["regime"].to_dict()
inicios = df_nan["Hora Início"].to_dict()
print(regimes)
display(inicios)

{0: 3, 1: 4, 2: 6}

{0: '00:00',
 1: '00:15',
 2: '00:30',
 3: '00:45',
 4: '01:00',
 5: '01:15',
 6: '01:30',
 7: '01:45',
 8: '02:00',
 9: '02:15',
 10: '02:30',
 11: '02:45',
 12: '03:00',
 13: '03:15',
 14: '03:30',
 15: '03:45',
 16: '04:00',
 17: '04:15',
 18: '04:30',
 19: '04:45',
 20: '05:00',
 21: '05:15',
 22: '05:30',
 23: '05:45',
 24: '06:00',
 25: '06:15',
 26: '06:30',
 27: '06:45',
 28: '07:00',
 29: '07:15',
 30: '07:30',
 31: '07:45',
 32: '08:00',
 33: '08:15',
 34: '08:30',
 35: '08:45',
 36: '09:00',
 37: '09:15',
 38: '09:30',
 39: '09:45',
 40: '10:00',
 41: '10:15',
 42: '10:30',
 43: '10:45',
 44: '11:00',
 45: '11:15',
 46: '11:30',
 47: '11:45',
 48: '12:00',
 49: '12:15',
 50: '12:30',
 51: '12:45',
 52: '13:00',
 53: '13:15',
 54: '13:30',
 55: '13:45',
 56: '14:00',
 57: '14:15',
 58: '14:30',
 59: '14:45',
 60: '15:00',
 61: '15:15',
 62: '15:30',
 63: '15:45',
 64: '16:00',
 65: '16:15',
 66: '16:30',
 67: '16:45',
 68: '17:00',
 69: '17:15',
 70: '17:30',
 71: '17:45',
 72: '18:00',
 73: '18:15',
 74: '18:30',
 75: '18:45',
 76: '19:00',
 77: '19:15',
 78: '19:30',
 79: '19:45',
 80: '20:00',
 81: '20:15',
 82: '20:30',
 83: '20:45',
 84: '21:00',
 85: '21:15',
 86: '21:30',
 87: '21:45',
 88: '22:00',
 89: '22:15',
 90: '22:30',
 91: '22:45',
 92: '23:00',
 93: '23:15',
 94: '23:30',
 95: '23:45'}

In [53]:
#vamos usar o itertools pra fazer a conta um com todos e todos com um 
#mas poderiamos fazer a mesma coisa usando 2 for, representando as somatorias
#igual na matematica 

lista_variaveis = list(product(regimes, inicios))
display(lista_variaveis)

[(0, 0),
 (0, 1),
 (0, 2),
 (0, 3),
 (0, 4),
 (0, 5),
 (0, 6),
 (0, 7),
 (0, 8),
 (0, 9),
 (0, 10),
 (0, 11),
 (0, 12),
 (0, 13),
 (0, 14),
 (0, 15),
 (0, 16),
 (0, 17),
 (0, 18),
 (0, 19),
 (0, 20),
 (0, 21),
 (0, 22),
 (0, 23),
 (0, 24),
 (0, 25),
 (0, 26),
 (0, 27),
 (0, 28),
 (0, 29),
 (0, 30),
 (0, 31),
 (0, 32),
 (0, 33),
 (0, 34),
 (0, 35),
 (0, 36),
 (0, 37),
 (0, 38),
 (0, 39),
 (0, 40),
 (0, 41),
 (0, 42),
 (0, 43),
 (0, 44),
 (0, 45),
 (0, 46),
 (0, 47),
 (0, 48),
 (0, 49),
 (0, 50),
 (0, 51),
 (0, 52),
 (0, 53),
 (0, 54),
 (0, 55),
 (0, 56),
 (0, 57),
 (0, 58),
 (0, 59),
 (0, 60),
 (0, 61),
 (0, 62),
 (0, 63),
 (0, 64),
 (0, 65),
 (0, 66),
 (0, 67),
 (0, 68),
 (0, 69),
 (0, 70),
 (0, 71),
 (0, 72),
 (0, 73),
 (0, 74),
 (0, 75),
 (0, 76),
 (0, 77),
 (0, 78),
 (0, 79),
 (0, 80),
 (0, 81),
 (0, 82),
 (0, 83),
 (0, 84),
 (0, 85),
 (0, 86),
 (0, 87),
 (0, 88),
 (0, 89),
 (0, 90),
 (0, 91),
 (0, 92),
 (0, 93),
 (0, 94),
 (0, 95),
 (1, 0),
 (1, 1),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (1, 7),
 (1, 8),
 (1, 9),
 (1, 10),
 (1, 11),
 (1, 12),
 (1, 13),
 (1, 14),
 (1, 15),
 (1, 16),
 (1, 17),
 (1, 18),
 (1, 19),
 (1, 20),
 (1, 21),
 (1, 22),
 (1, 23),
 (1, 24),
 (1, 25),
 (1, 26),
 (1, 27),
 (1, 28),
 (1, 29),
 (1, 30),
 (1, 31),
 (1, 32),
 (1, 33),
 (1, 34),
 (1, 35),
 (1, 36),
 (1, 37),
 (1, 38),
 (1, 39),
 (1, 40),
 (1, 41),
 (1, 42),
 (1, 43),
 (1, 44),
 (1, 45),
 (1, 46),
 (1, 47),
 (1, 48),
 (1, 49),
 (1, 50),
 (1, 51),
 (1, 52),
 (1, 53),
 (1, 54),
 (1, 55),
 (1, 56),
 (1, 57),
 (1, 58),
 (1, 59),
 (1, 60),
 (1, 61),
 (1, 62),
 (1, 63),
 (1, 64),
 (1, 65),
 (1, 66),
 (1, 67),
 (1, 68),
 (1, 69),
 (1, 70),
 (1, 71),
 (1, 72),
 (1, 73),
 (1, 74),
 (1, 75),
 (1, 76),
 (1, 77),
 (1, 78),
 (1, 79),
 (1, 80),
 (1, 81),
 (1, 82),
 (1, 83),
 (1, 84),
 (1, 85),
 (1, 86),
 (1, 87),
 (1, 88),
 (1, 89),
 (1, 90),
 (1, 91),
 (1, 92),
 (1, 93),
 (1, 94),
 (1, 95),
 (2, 0),
 (2, 1),
 (2, 2),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (2, 7),
 (2, 8),
 (2, 9),
 (2, 10),
 (2, 11),
 (2, 12),
 (2, 13),
 (2, 14),
 (2, 15),
 (2, 16),
 (2, 17),
 (2, 18),
 (2, 19),
 (2, 20),
 (2, 21),
 (2, 22),
 (2, 23),
 (2, 24),
 (2, 25),
 (2, 26),
 (2, 27),
 (2, 28),
 (2, 29),
 (2, 30),
 (2, 31),
 (2, 32),
 (2, 33),
 (2, 34),
 (2, 35),
 (2, 36),
 (2, 37),
 (2, 38),
 (2, 39),
 (2, 40),
 (2, 41),
 (2, 42),
 (2, 43),
 (2, 44),
 (2, 45),
 (2, 46),
 (2, 47),
 (2, 48),
 (2, 49),
 (2, 50),
 (2, 51),
 (2, 52),
 (2, 53),
 (2, 54),
 (2, 55),
 (2, 56),
 (2, 57),
 (2, 58),
 (2, 59),
 (2, 60),
 (2, 61),
 (2, 62),
 (2, 63),
 (2, 64),
 (2, 65),
 (2, 66),
 (2, 67),
 (2, 68),
 (2, 69),
 (2, 70),
 (2, 71),
 (2, 72),
 (2, 73),
 (2, 74),
 (2, 75),
 (2, 76),
 (2, 77),
 (2, 78),
 (2, 79),
 (2, 80),
 (2, 81),
 (2, 82),
 (2, 83),
 (2, 84),
 (2, 85),
 (2, 86),
 (2, 87),
 (2, 88),
 (2, 89),
 (2, 90),
 (2, 91),
 (2, 92),
 (2, 93),
 (2, 94),
 (2, 95)]

In [54]:
#Criando o problema
prob = plp.LpProblem(name = "Attentus", sense = plp.LpMinimize)

display(prob)

Attentus:
MINIMIZE
None
VARIABLES

In [63]:
dict_variaveis = plp.LpVariable.dicts(name = "A", indices = lista_variaveis, lowBound = 0, cat = plp.LpInteger)

In [66]:
lista_coeficientes = []

for indice_regime, indice_periodo in lista_variaveis:
    encargo = df_nad.loc[indice_regime, "enc"]
    lista_coeficientes.append(encargo)

print(lista_coeficientes[::50])

[np.int64(540), np.int64(540), np.int64(680), np.int64(680), np.int64(960), np.int64(960)]

In [68]:
lista_multiplicacoes = []

for coef, lpvariable in zip(lista_coeficientes, dict_variaveis.values()):
    lista_multiplicacoes.append(coef * lpvariable)

fo = sum(lista_multiplicacoes)
display(fo)

540*A_(0,_0) + 540*A_(0,_1) + 540*A_(0,_10) + 540*A_(0,_11) + 540*A_(0,_12) + 540*A_(0,_13) + 540*A_(0,_14) + 540*A_(0,_15) + 540*A_(0,_16) + 540*A_(0,_17) + 540*A_(0,_18) + 540*A_(0,_19) + 540*A_(0,_2) + 540*A_(0,_20) + 540*A_(0,_21) + 540*A_(0,_22) + 540*A_(0,_23) + 540*A_(0,_24) + 540*A_(0,_25) + 540*A_(0,_26) + 540*A_(0,_27) + 540*A_(0,_28) + 540*A_(0,_29) + 540*A_(0,_3) + 540*A_(0,_30) + 540*A_(0,_31) + 540*A_(0,_32) + 540*A_(0,_33) + 540*A_(0,_34) + 540*A_(0,_35) + 540*A_(0,_36) + 540*A_(0,_37) + 540*A_(0,_38) + 540*A_(0,_39) + 540*A_(0,_4) + 540*A_(0,_40) + 540*A_(0,_41) + 540*A_(0,_42) + 540*A_(0,_43) + 540*A_(0,_44) + 540*A_(0,_45) + 540*A_(0,_46) + 540*A_(0,_47) + 540*A_(0,_48) + 540*A_(0,_49) + 540*A_(0,_5) + 540*A_(0,_50) + 540*A_(0,_51) + 540*A_(0,_52) + 540*A_(0,_53) + 540*A_(0,_54) + 540*A_(0,_55) + 540*A_(0,_56) + 540*A_(0,_57) + 540*A_(0,_58) + 540*A_(0,_59) + 540*A_(0,_6) + 540*A_(0,_60) + 540*A_(0,_61) + 540*A_(0,_62) + 540*A_(0,_63) + 540*A_(0,_64) + 540*A_(0,_65) + 540*A_(0,_66) + 540*A_(0,_67) + 540*A_(0,_68) + 540*A_(0,_69) + 540*A_(0,_7) + 540*A_(0,_70) + 540*A_(0,_71) + 540*A_(0,_72) + 540*A_(0,_73) + 540*A_(0,_74) + 540*A_(0,_75) + 540*A_(0,_76) + 540*A_(0,_77) + 540*A_(0,_78) + 540*A_(0,_79) + 540*A_(0,_8) + 540*A_(0,_80) + 540*A_(0,_81) + 540*A_(0,_82) + 540*A_(0,_83) + 540*A_(0,_84) + 540*A_(0,_85) + 540*A_(0,_86) + 540*A_(0,_87) + 540*A_(0,_88) + 540*A_(0,_89) + 540*A_(0,_9) + 540*A_(0,_90) + 540*A_(0,_91) + 540*A_(0,_92) + 540*A_(0,_93) + 540*A_(0,_94) + 540*A_(0,_95) + 680*A_(1,_0) + 680*A_(1,_1) + 680*A_(1,_10) + 680*A_(1,_11) + 680*A_(1,_12) + 680*A_(1,_13) + 680*A_(1,_14) + 680*A_(1,_15) + 680*A_(1,_16) + 680*A_(1,_17) + 680*A_(1,_18) + 680*A_(1,_19) + 680*A_(1,_2) + 680*A_(1,_20) + 680*A_(1,_21) + 680*A_(1,_22) + 680*A_(1,_23) + 680*A_(1,_24) + 680*A_(1,_25) + 680*A_(1,_26) + 680*A_(1,_27) + 680*A_(1,_28) + 680*A_(1,_29) + 680*A_(1,_3) + 680*A_(1,_30) + 680*A_(1,_31) + 680*A_(1,_32) + 680*A_(1,_33) + 680*A_(1,_34) + 680*A_(1,_35) + 680*A_(1,_36) + 680*A_(1,_37) + 680*A_(1,_38) + 680*A_(1,_39) + 680*A_(1,_4) + 680*A_(1,_40) + 680*A_(1,_41) + 680*A_(1,_42) + 680*A_(1,_43) + 680*A_(1,_44) + 680*A_(1,_45) + 680*A_(1,_46) + 680*A_(1,_47) + 680*A_(1,_48) + 680*A_(1,_49) + 680*A_(1,_5) + 680*A_(1,_50) + 680*A_(1,_51) + 680*A_(1,_52) + 680*A_(1,_53) + 680*A_(1,_54) + 680*A_(1,_55) + 680*A_(1,_56) + 680*A_(1,_57) + 680*A_(1,_58) + 680*A_(1,_59) + 680*A_(1,_6) + 680*A_(1,_60) + 680*A_(1,_61) + 680*A_(1,_62) + 680*A_(1,_63) + 680*A_(1,_64) + 680*A_(1,_65) + 680*A_(1,_66) + 680*A_(1,_67) + 680*A_(1,_68) + 680*A_(1,_69) + 680*A_(1,_7) + 680*A_(1,_70) + 680*A_(1,_71) + 680*A_(1,_72) + 680*A_(1,_73) + 680*A_(1,_74) + 680*A_(1,_75) + 680*A_(1,_76) + 680*A_(1,_77) + 680*A_(1,_78) + 680*A_(1,_79) + 680*A_(1,_8) + 680*A_(1,_80) + 680*A_(1,_81) + 680*A_(1,_82) + 680*A_(1,_83) + 680*A_(1,_84) + 680*A_(1,_85) + 680*A_(1,_86) + 680*A_(1,_87) + 680*A_(1,_88) + 680*A_(1,_89) + 680*A_(1,_9) + 680*A_(1,_90) + 680*A_(1,_91) + 680*A_(1,_92) + 680*A_(1,_93) + 680*A_(1,_94) + 680*A_(1,_95) + 960*A_(2,_0) + 960*A_(2,_1) + 960*A_(2,_10) + 960*A_(2,_11) + 960*A_(2,_12) + 960*A_(2,_13) + 960*A_(2,_14) + 960*A_(2,_15) + 960*A_(2,_16) + 960*A_(2,_17) + 960*A_(2,_18) + 960*A_(2,_19) + 960*A_(2,_2) + 960*A_(2,_20) + 960*A_(2,_21) + 960*A_(2,_22) + 960*A_(2,_23) + 960*A_(2,_24) + 960*A_(2,_25) + 960*A_(2,_26) + 960*A_(2,_27) + 960*A_(2,_28) + 960*A_(2,_29) + 960*A_(2,_3) + 960*A_(2,_30) + 960*A_(2,_31) + 960*A_(2,_32) + 960*A_(2,_33) + 960*A_(2,_34) + 960*A_(2,_35) + 960*A_(2,_36) + 960*A_(2,_37) + 960*A_(2,_38) + 960*A_(2,_39) + 960*A_(2,_4) + 960*A_(2,_40) + 960*A_(2,_41) + 960*A_(2,_42) + 960*A_(2,_43) + 960*A_(2,_44) + 960*A_(2,_45) + 960*A_(2,_46) + 960*A_(2,_47) + 960*A_(2,_48) + 960*A_(2,_49) + 960*A_(2,_5) + 960*A_(2,_50) + 960*A_(2,_51) + 960*A_(2,_52) + 960*A_(2,_53) + 960*A_(2,_54) + 960*A_(2,_55) + 960*A_(2,_56) + 960*A_(2,_57) + 960*A_(2,_58) + 960*A_(2,_59) + 960*A_(2,_6) + 960*A_(2,_60) + 960*A_(2,_61) + 960*A_(2,_62) + 960*A_(2,_63) + 960*A_(2,_64) + 960*A_(2,_65) + 960*A_(2,_66) + 960*A_(2,_67) + 960*A_(2,_68) + 960*A_(2,_69) + 960*A_(2,_7) + 960*A_(2,_70) + 960*A_(2,_71) + 960*A_(2,_72) + 960*A_(2,_73) + 960*A_(2,_74) + 960*A_(2,_75) + 960*A_(2,_76) + 960*A_(2,_77) + 960*A_(2,_78) + 960*A_(2,_79) + 960*A_(2,_8) + 960*A_(2,_80) + 960*A_(2,_81) + 960*A_(2,_82) + 960*A_(2,_83) + 960*A_(2,_84) + 960*A_(2,_85) + 960*A_(2,_86) + 960*A_(2,_87) + 960*A_(2,_88) + 960*A_(2,_89) + 960*A_(2,_9) + 960*A_(2,_90) + 960*A_(2,_91) + 960*A_(2,_92) + 960*A_(2,_93) + 960*A_(2,_94) + 960*A_(2,_95) + 0

In [69]:
display(type(fo))

pulp.pulp.LpAffineExpression

In [70]:
prob += fo, "Custo"
display(prob)

Attentus:
MINIMIZE
540*A_(0,_0) + 540*A_(0,_1) + 540*A_(0,_10) + 540*A_(0,_11) + 540*A_(0,_12) + 540*A_(0,_13) + 540*A_(0,_14) + 540*A_(0,_15) + 540*A_(0,_16) + 540*A_(0,_17) + 540*A_(0,_18) + 540*A_(0,_19) + 540*A_(0,_2) + 540*A_(0,_20) + 540*A_(0,_21) + 540*A_(0,_22) + 540*A_(0,_23) + 540*A_(0,_24) + 540*A_(0,_25) + 540*A_(0,_26) + 540*A_(0,_27) + 540*A_(0,_28) + 540*A_(0,_29) + 540*A_(0,_3) + 540*A_(0,_30) + 540*A_(0,_31) + 540*A_(0,_32) + 540*A_(0,_33) + 540*A_(0,_34) + 540*A_(0,_35) + 540*A_(0,_36) + 540*A_(0,_37) + 540*A_(0,_38) + 540*A_(0,_39) + 540*A_(0,_4) + 540*A_(0,_40) + 540*A_(0,_41) + 540*A_(0,_42) + 540*A_(0,_43) + 540*A_(0,_44) + 540*A_(0,_45) + 540*A_(0,_46) + 540*A_(0,_47) + 540*A_(0,_48) + 540*A_(0,_49) + 540*A_(0,_5) + 540*A_(0,_50) + 540*A_(0,_51) + 540*A_(0,_52) + 540*A_(0,_53) + 540*A_(0,_54) + 540*A_(0,_55) + 540*A_(0,_56) + 540*A_(0,_57) + 540*A_(0,_58) + 540*A_(0,_59) + 540*A_(0,_6) + 540*A_(0,_60) + 540*A_(0,_61) + 540*A_(0,_62) + 540*A_(0,_63) + 540*A_(0,_64) + 540*A_(0,_65) + 540*A_(0,_66) + 540*A_(0,_67) + 540*A_(0,_68) + 540*A_(0,_69) + 540*A_(0,_7) + 540*A_(0,_70) + 540*A_(0,_71) + 540*A_(0,_72) + 540*A_(0,_73) + 540*A_(0,_74) + 540*A_(0,_75) + 540*A_(0,_76) + 540*A_(0,_77) + 540*A_(0,_78) + 540*A_(0,_79) + 540*A_(0,_8) + 540*A_(0,_80) + 540*A_(0,_81) + 540*A_(0,_82) + 540*A_(0,_83) + 540*A_(0,_84) + 540*A_(0,_85) + 540*A_(0,_86) + 540*A_(0,_87) + 540*A_(0,_88) + 540*A_(0,_89) + 540*A_(0,_9) + 540*A_(0,_90) + 540*A_(0,_91) + 540*A_(0,_92) + 540*A_(0,_93) + 540*A_(0,_94) + 540*A_(0,_95) + 680*A_(1,_0) + 680*A_(1,_1) + 680*A_(1,_10) + 680*A_(1,_11) + 680*A_(1,_12) + 680*A_(1,_13) + 680*A_(1,_14) + 680*A_(1,_15) + 680*A_(1,_16) + 680*A_(1,_17) + 680*A_(1,_18) + 680*A_(1,_19) + 680*A_(1,_2) + 680*A_(1,_20) + 680*A_(1,_21) + 680*A_(1,_22) + 680*A_(1,_23) + 680*A_(1,_24) + 680*A_(1,_25) + 680*A_(1,_26) + 680*A_(1,_27) + 680*A_(1,_28) + 680*A_(1,_29) + 680*A_(1,_3) + 680*A_(1,_30) + 680*A_(1,_31) + 680*A_(1,_32) + 680*A_(1,_33) + 680*A_(1,_34) + 680*A_(1,_35) + 680*A_(1,_36) + 680*A_(1,_37) + 680*A_(1,_38) + 680*A_(1,_39) + 680*A_(1,_4) + 680*A_(1,_40) + 680*A_(1,_41) + 680*A_(1,_42) + 680*A_(1,_43) + 680*A_(1,_44) + 680*A_(1,_45) + 680*A_(1,_46) + 680*A_(1,_47) + 680*A_(1,_48) + 680*A_(1,_49) + 680*A_(1,_5) + 680*A_(1,_50) + 680*A_(1,_51) + 680*A_(1,_52) + 680*A_(1,_53) + 680*A_(1,_54) + 680*A_(1,_55) + 680*A_(1,_56) + 680*A_(1,_57) + 680*A_(1,_58) + 680*A_(1,_59) + 680*A_(1,_6) + 680*A_(1,_60) + 680*A_(1,_61) + 680*A_(1,_62) + 680*A_(1,_63) + 680*A_(1,_64) + 680*A_(1,_65) + 680*A_(1,_66) + 680*A_(1,_67) + 680*A_(1,_68) + 680*A_(1,_69) + 680*A_(1,_7) + 680*A_(1,_70) + 680*A_(1,_71) + 680*A_(1,_72) + 680*A_(1,_73) + 680*A_(1,_74) + 680*A_(1,_75) + 680*A_(1,_76) + 680*A_(1,_77) + 680*A_(1,_78) + 680*A_(1,_79) + 680*A_(1,_8) + 680*A_(1,_80) + 680*A_(1,_81) + 680*A_(1,_82) + 680*A_(1,_83) + 680*A_(1,_84) + 680*A_(1,_85) + 680*A_(1,_86) + 680*A_(1,_87) + 680*A_(1,_88) + 680*A_(1,_89) + 680*A_(1,_9) + 680*A_(1,_90) + 680*A_(1,_91) + 680*A_(1,_92) + 680*A_(1,_93) + 680*A_(1,_94) + 680*A_(1,_95) + 960*A_(2,_0) + 960*A_(2,_1) + 960*A_(2,_10) + 960*A_(2,_11) + 960*A_(2,_12) + 960*A_(2,_13) + 960*A_(2,_14) + 960*A_(2,_15) + 960*A_(2,_16) + 960*A_(2,_17) + 960*A_(2,_18) + 960*A_(2,_19) + 960*A_(2,_2) + 960*A_(2,_20) + 960*A_(2,_21) + 960*A_(2,_22) + 960*A_(2,_23) + 960*A_(2,_24) + 960*A_(2,_25) + 960*A_(2,_26) + 960*A_(2,_27) + 960*A_(2,_28) + 960*A_(2,_29) + 960*A_(2,_3) + 960*A_(2,_30) + 960*A_(2,_31) + 960*A_(2,_32) + 960*A_(2,_33) + 960*A_(2,_34) + 960*A_(2,_35) + 960*A_(2,_36) + 960*A_(2,_37) + 960*A_(2,_38) + 960*A_(2,_39) + 960*A_(2,_4) + 960*A_(2,_40) + 960*A_(2,_41) + 960*A_(2,_42) + 960*A_(2,_43) + 960*A_(2,_44) + 960*A_(2,_45) + 960*A_(2,_46) + 960*A_(2,_47) + 960*A_(2,_48) + 960*A_(2,_49) + 960*A_(2,_5) + 960*A_(2,_50) + 960*A_(2,_51) + 960*A_(2,_52) + 960*A_(2,_53) + 960*A_(2,_54) + 960*A_(2,_55) + 960*A_(2,_56) + 960*A_(2,_57) + 960*A_(2,_58) + 960*A_(2,_59) + 960*A_(2,_6) + 960*A_(2,_60) + 960*A_(2,_61) + 960*A_(2,_62) + 960*A_(2,_63) + 960*A_(2,_64) + 960*A_(2,_65) + 960*A_(2,_66) + 960*A_(2,_67) + 960*A_(2,_68) + 960*A_(2,_69) + 960*A_(2,_7) + 960*A_(2,_70) + 960*A_(2,_71) + 960*A_(2,_72) + 960*A_(2,_73) + 960*A_(2,_74) + 960*A_(2,_75) + 960*A_(2,_76) + 960*A_(2,_77) + 960*A_(2,_78) + 960*A_(2,_79) + 960*A_(2,_8) + 960*A_(2,_80) + 960*A_(2,_81) + 960*A_(2,_82) + 960*A_(2,_83) + 960*A_(2,_84) + 960*A_(2,_85) + 960*A_(2,_86) + 960*A_(2,_87) + 960*A_(2,_88) + 960*A_(2,_89) + 960*A_(2,_9) + 960*A_(2,_90) + 960*A_(2,_91) + 960*A_(2,_92) + 960*A_(2,_93) + 960*A_(2,_94) + 960*A_(2,_95) + 0
VARIABLES
0 <= A_(0,_0) Integer
0 <= A_(0,_1) Integer
0 <= A_(0,_10) Integer
0 <= A_(0,_11) Integer
0 <= A_(0,_12) Integer
0 <= A_(0,_13) Integer
0 <= A_(0,_14) Integer
0 <= A_(0,_15) Integer
0 <= A_(0,_16) Integer
0 <= A_(0,_17) Integer
0 <= A_(0,_18) Integer
0 <= A_(0,_19) Integer
0 <= A_(0,_2) Integer
0 <= A_(0,_20) Integer
0 <= A_(0,_21) Integer
0 <= A_(0,_22) Integer
0 <= A_(0,_23) Integer
0 <= A_(0,_24) Integer
0 <= A_(0,_25) Integer
0 <= A_(0,_26) Integer
0 <= A_(0,_27) Integer
0 <= A_(0,_28) Integer
0 <= A_(0,_29) Integer
0 <= A_(0,_3) Integer
0 <= A_(0,_30) Integer
0 <= A_(0,_31) Integer
0 <= A_(0,_32) Integer
0 <= A_(0,_33) Integer
0 <= A_(0,_34) Integer
0 <= A_(0,_35) Integer
0 <= A_(0,_36) Integer
0 <= A_(0,_37) Integer
0 <= A_(0,_38) Integer
0 <= A_(0,_39) Integer
0 <= A_(0,_4) Integer
0 <= A_(0,_40) Integer
0 <= A_(0,_41) Integer
0 <= A_(0,_42) Integer
0 <= A_(0,_43) Integer
0 <= A_(0,_44) Integer
0 <= A_(0,_45) Integer
0 <= A_(0,_46) Integer
0 <= A_(0,_47) Integer
0 <= A_(0,_48) Integer
0 <= A_(0,_49) Integer
0 <= A_(0,_5) Integer
0 <= A_(0,_50) Integer
0 <= A_(0,_51) Integer
0 <= A_(0,_52) Integer
0 <= A_(0,_53) Integer
0 <= A_(0,_54) Integer
0 <= A_(0,_55) Integer
0 <= A_(0,_56) Integer
0 <= A_(0,_57) Integer
0 <= A_(0,_58) Integer
0 <= A_(0,_59) Integer
0 <= A_(0,_6) Integer
0 <= A_(0,_60) Integer
0 <= A_(0,_61) Integer
0 <= A_(0,_62) Integer
0 <= A_(0,_63) Integer
0 <= A_(0,_64) Integer
0 <= A_(0,_65) Integer
0 <= A_(0,_66) Integer
0 <= A_(0,_67) Integer
0 <= A_(0,_68) Integer
0 <= A_(0,_69) Integer
0 <= A_(0,_7) Integer
0 <= A_(0,_70) Integer
0 <= A_(0,_71) Integer
0 <= A_(0,_72) Integer
0 <= A_(0,_73) Integer
0 <= A_(0,_74) Integer
0 <= A_(0,_75) Integer
0 <= A_(0,_76) Integer
0 <= A_(0,_77) Integer
0 <= A_(0,_78) Integer
0 <= A_(0,_79) Integer
0 <= A_(0,_8) Integer
0 <= A_(0,_80) Integer
0 <= A_(0,_81) Integer
0 <= A_(0,_82) Integer
0 <= A_(0,_83) Integer
0 <= A_(0,_84) Integer
0 <= A_(0,_85) Integer
0 <= A_(0,_86) Integer
0 <= A_(0,_87) Integer
0 <= A_(0,_88) Integer
0 <= A_(0,_89) Integer
0 <= A_(0,_9) Integer
0 <= A_(0,_90) Integer
0 <= A_(0,_91) Integer
0 <= A_(0,_92) Integer
0 <= A_(0,_93) Integer
0 <= A_(0,_94) Integer
0 <= A_(0,_95) Integer
0 <= A_(1,_0) Integer
0 <= A_(1,_1) Integer
0 <= A_(1,_10) Integer
0 <= A_(1,_11) Integer
0 <= A_(1,_12) Integer
0 <= A_(1,_13) Integer
0 <= A_(1,_14) Integer
0 <= A_(1,_15) Integer
0 <= A_(1,_16) Integer
0 <= A_(1,_17) Integer
0 <= A_(1,_18) Integer
0 <= A_(1,_19) Integer
0 <= A_(1,_2) Integer
0 <= A_(1,_20) Integer
0 <= A_(1,_21) Integer
0 <= A_(1,_22) Integer
0 <= A_(1,_23) Integer
0 <= A_(1,_24) Integer
0 <= A_(1,_25) Integer
0 <= A_(1,_26) Integer
0 <= A_(1,_27) Integer
0 <= A_(1,_28) Integer
0 <= A_(1,_29) Integer
0 <= A_(1,_3) Integer
0 <= A_(1,_30) Integer
0 <= A_(1,_31) Integer
0 <= A_(1,_32) Integer
0 <= A_(1,_33) Integer
0 <= A_(1,_34) Integer
0 <= A_(1,_35) Integer
0 <= A_(1,_36) Integer
0 <= A_(1,_37) Integer
0 <= A_(1,_38) Integer
0 <= A_(1,_39) Integer
0 <= A_(1,_4) Integer
0 <= A_(1,_40) Integer
0 <= A_(1,_41) Integer
0 <= A_(1,_42) Integer
0 <= A_(1,_43) Integer
0 <= A_(1,_44) Integer
0 <= A_(1,_45) Integer
0 <= A_(1,_46) Integer
0 <= A_(1,_47) Integer
0 <= A_(1,_48) Integer
0 <= A_(1,_49) Integer
0 <= A_(1,_5) Integer
0 <= A_(1,_50) Integer
0 <= A_(1,_51) Integer
0 <= A_(1,_52) Integer
0 <= A_(1,_53) Integer
0 <= A_(1,_54) Integer
0 <= A_(1,_55) Integer
0 <= A_(1,_56) Integer
0 <= A_(1,_57) Integer
0 <= A_(1,_58) Integer
0 <= A_(1,_59) Integer
0 <= A_(1,_6) Integer
0 <= A_(1,_60) Integer
0 <= A_(1,_61) Integer
0 <= A_(1,_62) Integer
0 <= A_(1,_63) Integer
0 <= A_(1,_64) Integer
0 <= A_(1,_65) Integer
0 <= A_(1,_66) Integer
0 <= A_(1,_67) Integer
0 <= A_(1,_68) Integer
0 <= A_(1,_69) Integer
0 <= A_(1,_7) Integer
0 <= A_(1,_70) Integer
0 <= A_(1,_71) Integer
0 <= A_(1,_72) Integer
0 <= A_(1,_73) Integer
0 <= A_(1,_74) Integer
0 <= A_(1,_75) Integer
0 <= A_(1,_76) Integer
0 <= A_(1,_77) Integer
0 <= A_(1,_78) Integer
0 <= A_(1,_79) Integer
0 <= A_(1,_8) Integer
0 <= A_(1,_80) Integer
0 <= A_(1,_81) Integer
0 <= A_(1,_82) Integer
0 <= A_(1,_83) Integer
0 <= A_(1,_84) Integer
0 <= A_(1,_85) Integer
0 <= A_(1,_86) Integer
0 <= A_(1,_87) Integer
0 <= A_(1,_88) Integer
0 <= A_(1,_89) Integer
0 <= A_(1,_9) Integer
0 <= A_(1,_90) Integer
0 <= A_(1,_91) Integer
0 <= A_(1,_92) Integer
0 <= A_(1,_93) Integer
0 <= A_(1,_94) Integer
0 <= A_(1,_95) Integer
0 <= A_(2,_0) Integer
0 <= A_(2,_1) Integer
0 <= A_(2,_10) Integer
0 <= A_(2,_11) Integer
0 <= A_(2,_12) Integer
0 <= A_(2,_13) Integer
0 <= A_(2,_14) Integer
0 <= A_(2,_15) Integer
0 <= A_(2,_16) Integer
0 <= A_(2,_17) Integer
0 <= A_(2,_18) Integer
0 <= A_(2,_19) Integer
0 <= A_(2,_2) Integer
0 <= A_(2,_20) Integer
0 <= A_(2,_21) Integer
0 <= A_(2,_22) Integer
0 <= A_(2,_23) Integer
0 <= A_(2,_24) Integer
0 <= A_(2,_25) Integer
0 <= A_(2,_26) Integer
0 <= A_(2,_27) Integer
0 <= A_(2,_28) Integer
0 <= A_(2,_29) Integer
0 <= A_(2,_3) Integer
0 <= A_(2,_30) Integer
0 <= A_(2,_31) Integer
0 <= A_(2,_32) Integer
0 <= A_(2,_33) Integer
0 <= A_(2,_34) Integer
0 <= A_(2,_35) Integer
0 <= A_(2,_36) Integer
0 <= A_(2,_37) Integer
0 <= A_(2,_38) Integer
0 <= A_(2,_39) Integer
0 <= A_(2,_4) Integer
0 <= A_(2,_40) Integer
0 <= A_(2,_41) Integer
0 <= A_(2,_42) Integer
0 <= A_(2,_43) Integer
0 <= A_(2,_44) Integer
0 <= A_(2,_45) Integer
0 <= A_(2,_46) Integer
0 <= A_(2,_47) Integer
0 <= A_(2,_48) Integer
0 <= A_(2,_49) Integer
0 <= A_(2,_5) Integer
0 <= A_(2,_50) Integer
0 <= A_(2,_51) Integer
0 <= A_(2,_52) Integer
0 <= A_(2,_53) Integer
0 <= A_(2,_54) Integer
0 <= A_(2,_55) Integer
0 <= A_(2,_56) Integer
0 <= A_(2,_57) Integer
0 <= A_(2,_58) Integer
0 <= A_(2,_59) Integer
0 <= A_(2,_6) Integer
0 <= A_(2,_60) Integer
0 <= A_(2,_61) Integer
0 <= A_(2,_62) Integer
0 <= A_(2,_63) Integer
0 <= A_(2,_64) Integer
0 <= A_(2,_65) Integer
0 <= A_(2,_66) Integer
0 <= A_(2,_67) Integer
0 <= A_(2,_68) Integer
0 <= A_(2,_69) Integer
0 <= A_(2,_7) Integer
0 <= A_(2,_70) Integer
0 <= A_(2,_71) Integer
0 <= A_(2,_72) Integer
0 <= A_(2,_73) Integer
0 <= A_(2,_74) Integer
0 <= A_(2,_75) Integer
0 <= A_(2,_76) Integer
0 <= A_(2,_77) Integer
0 <= A_(2,_78) Integer
0 <= A_(2,_79) Integer
0 <= A_(2,_8) Integer
0 <= A_(2,_80) Integer
0 <= A_(2,_81) Integer
0 <= A_(2,_82) Integer
0 <= A_(2,_83) Integer
0 <= A_(2,_84) Integer
0 <= A_(2,_85) Integer
0 <= A_(2,_86) Integer
0 <= A_(2,_87) Integer
0 <= A_(2,_88) Integer
0 <= A_(2,_89) Integer
0 <= A_(2,_9) Integer
0 <= A_(2,_90) Integer
0 <= A_(2,_91) Integer
0 <= A_(2,_92) Integer
0 <= A_(2,_93) Integer
0 <= A_(2,_94) Integer
0 <= A_(2,_95) Integer

In [71]:
k = 3
lista = [0,1,2,3,4,5,6,7]

In [72]:
print(lista[0:3])
print(lista[1:4])
print(lista[2:5])

[0, 1, 2]
[1, 2, 3]
[2, 3, 4]

In [73]:
k=12
z = len(inicios)
inicios_duplicados = 2 * list(inicios.keys())

print(inicios_duplicados[z-k+0+1:z+0+1]) # k=12 | z=96 | j=0
print(inicios_duplicados[z-k+1+1:z+1+1]) # k=12 | z=96 | j=1
print(inicios_duplicados[z-k+2+1:z+2+1])  # k=12 | z=96 | j=2
print(inicios_duplicados[z-k+3+1:z+3+1])    # k=12 | z=96 | j=3
print(inicios_duplicados[z-k+95+1:z+95+1])  # k=12 | z=96 | j=95

[85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 0]
[86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 0, 1]
[87, 88, 89, 90, 91, 92, 93, 94, 95, 0, 1, 2]
[88, 89, 90, 91, 92, 93, 94, 95, 0, 1, 2, 3]
[84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]

In [74]:
def retorna_sublista(lista, k, j):
    z = len(inicios)
    lista_duplicada = 2 * lista
    return lista_duplicada[z-k+j+1 : z+j+1]

print(retorna_sublista(list(inicios), k=12, j=95))

[84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]

In [75]:
for indice_inicio, nome_inicio in inicios.items():
    print(indice_inicio, nome_inicio)

0 00:00
1 00:15
2 00:30
3 00:45
4 01:00
5 01:15
6 01:30
7 01:45
8 02:00
9 02:15
10 02:30
11 02:45
12 03:00
13 03:15
14 03:30
15 03:45
16 04:00
17 04:15
18 04:30
19 04:45
20 05:00
21 05:15
22 05:30
23 05:45
24 06:00
25 06:15
26 06:30
27 06:45
28 07:00
29 07:15
30 07:30
31 07:45
32 08:00
33 08:15
34 08:30
35 08:45
36 09:00
37 09:15
38 09:30
39 09:45
40 10:00
41 10:15
42 10:30
43 10:45
44 11:00
45 11:15
46 11:30
47 11:45
48 12:00
49 12:15
50 12:30
51 12:45
52 13:00
53 13:15
54 13:30
55 13:45
56 14:00
57 14:15
58 14:30
59 14:45
60 15:00
61 15:15
62 15:30
63 15:45
64 16:00
65 16:15
66 16:30
67 16:45
68 17:00
69 17:15
70 17:30
71 17:45
72 18:00
73 18:15
74 18:30
75 18:45
76 19:00
77 19:15
78 19:30
79 19:45
80 20:00
81 20:15
82 20:30
83 20:45
84 21:00
85 21:15
86 21:30
87 21:45
88 22:00
89 22:15
90 22:30
91 22:45
92 23:00
93 23:15
94 23:30
95 23:45